### ISSUE TITLE
How to add a switch?

### ISSUE THREAD

**Issue by Swiftnesses** [nklerk/nl.nielsdeklerk.neeo#12]
Hi,

I've added a new virtual device which contains a switch. How do I get this to show in NEEO?

Many thanks,

Mark

**Comment by nklerk** [comment]
Open the NEEO App, add a device and search for the name that you gave the virtual device.

**Comment by Swiftnesses** [comment]
Tried that... The device is added, but it doesn't show on the remote or in the app? I added an accessory with one switch.

**Comment by nklerk** [comment]
NEEO doesn’t show accessorie devices as recipies, you’ll have to add a shortcut to the place you want the switch exposed.

Met vriendelijke groet,

Niels de Klerk

(Privé)
M: +31 (0) 6 247 683 88
@: ‪Mail@Nielsdeklerk.nl
A: Koraalzwamplantsoen 6, 3451HK Vleuten

**Comment by Swiftnesses** [comment]
Hi Niels,

That's a shame... It would be the ideal way to make an awesome UI linked to Homey :(

What is the best way to do this?

**Comment by Swiftnesses** [comment]
Use case: I need a toggle for if my little boy is sleeping or not...

**Comment by nklerk** [comment]
Just add the shortcut on the light recipe. Or create a virtual TV and add a switch there. Just name the device whatever you like.

Met vriendelijke groet,

Niels de Klerk

(Privé)
M: +31 (0) 6 247 683 88
@: ‪Mail@Nielsdeklerk.nl
A: Koraalzwamplantsoen 6, 3451HK Vleuten

**Comment by nklerk** [comment]
an alternative is to 

1. create a new virtual device with type gameconsole. add a switch and other capabilities you would like.
2. Using the NEEO app add the device.
3. Then use the NEEO app and go to settings -> Recipes.
4. Hide the newly added Gameconsole device. (setting the recipe switch off)
5. Now select Create new recipe
6. Use the if... "Icon is pressed (on home screen)" option
7. tap "Add step"
8. Select the "Show controls" option and select the device you've just added and hide.
9. Save the recipe.
10. Start the recipe on the home screen and add a shortcut.

**Comment by Swiftnesses** [comment]
I'll try this... it's a real shame such a workaround is required :(

**Comment by nklerk** [comment]
If you want to use a UI for something that it’s not designed for then you generally need workarounds. However it’s still not blocking you to do so.
