### ISSUE TITLE
Your ... might need a little help....

### ISSUE THREAD

**Issue by jacquesvzijp** [nklerk/nl.nielsdeklerk.neeo#17]
Hi 
Fantastic piece of work this app and I can nicely create an interface now to my Bose Soundtouch using Neeo remote and Homey for the communication to the device.
However, why do I get the Your [Bose Soundtouch] might need a little help, Select the correct input manually dialogue on my remote when i start the device (I have to do the "when it's ready swipe left"  like any Need dumb device. Anyway to get rid of that?
Thanks a lot!
Jacques

**Comment by nklerk** [comment]
NEEO is missing an INPUT command button.
Add for instance INPUT HDMI 1 with my app. now remove the driver from NEEO and then Add it again. now it should be over.

Keep in mind that the naming is very important. even if you dont need specifically a button named "INPUT HDMI 1" add it anyway.

**Comment by jacquesvzijp** [comment]
Thanks Niels. That works. I still get the primary "shortcuts" screen showing INPUt HMDI 1 and then the second with my own shortcuts but I guess that is standard NEEO behaviour as with all other devices which cannot (yet) be changed. Let trust they will change that at some point!
