### ISSUE TITLE
Not compatible with Homey 2.0 software due to app.json settings

### ISSUE THREAD

**Issue by jordenc** [nklerk/nl.nielsdeklerk.neeo#27]
Current app.json => https://github.com/nklerk/nl.nielsdeklerk.neeo/blob/7cfcdb7a07479a19af7c0f7adbbf2ec0a1ed9610/app.json
it has:
"compatibility": "1.x >=1.5.0",

This means 2.x is not supported

**Comment by nklerk** [comment]
De beta version was approved today, I have just published that one.
This app version was meant to be released together with NEEO version 0.52.x due to new features.

**Comment by nklerk** [comment]
Both products where about to release big changes in their firmware. for my development this was less then ideal. I placed my bets on NEEO being the first to release their new firmware as back then the homey firmware wasn't available to beta and I had allready access to the upcomming NEEO firmware.

Please let me know if there are issues with the just published beta. as it was aimed for NEEO 0.52 and later.
